export enum IngredientType {
  VEGETABLE,
  FRUIT,
  MEAT,
  FISH,
  SEA_FRUIT,
  DAIRY,
  CHEESE,
  GRAIN,
  SPICE,
  CONDIMENT,
  NUT,
  HERBS,
  FAT,
  SUGAR,
  BEVERAGE,
  ALCOHOL,
  STARCHES,
  OTHER,
}

export const IngredientTypeLabel: Record<IngredientType, string> = {
  [IngredientType.VEGETABLE]: 'ingredientType.vegetable',
  [IngredientType.FRUIT]: 'ingredientType.fruit',
  [IngredientType.MEAT]: 'ingredientType.meat',
  [IngredientType.FISH]: 'ingredientType.fish',
  [IngredientType.SEA_FRUIT]: 'ingredientType.seaFruit',
  [IngredientType.DAIRY]: 'ingredientType.dairy',
  [IngredientType.CHEESE]: 'ingredientType.cheese',
  [IngredientType.GRAIN]: 'ingredientType.grain',
  [IngredientType.SPICE]: 'ingredientType.spice',
  [IngredientType.CONDIMENT]: 'ingredientType.condiment',
  [IngredientType.NUT]: 'ingredientType.nut',
  [IngredientType.HERBS]: 'ingredientType.herbs',
  [IngredientType.FAT]: 'ingredientType.fat',
  [IngredientType.SUGAR]: 'ingredientType.sugar',
  [IngredientType.BEVERAGE]: 'ingredientType.beverage',
  [IngredientType.ALCOHOL]: 'ingredientType.alcohol',
  [IngredientType.STARCHES]: 'ingredientType.starches',
  [IngredientType.OTHER]: 'ingredientType.orher',
};
