export enum IngredientType {
  VEGETABLE = 'VEGETABLE',
  FRUIT = 'FRUIT',
  MEAT = 'MEAT',
  FISH = 'FISH',
  SEA_FRUIT = 'SEA_FRUIT',
  DAIRY = 'DAIRY',
  CHEESE = 'CHEESE',
  GRAIN = 'GRAIN',
  SPICE = 'SPICE',
  CONDIMENT = 'CONDIMENT',
  NUT = 'NUT',
  HERBS = 'HERBS',
  FAT = 'FAT',
  SUGAR = 'SUGAR',
  BEVERAGE = 'BEVERAGE',
  ALCOHOL = 'ALCOHOL',
  STARCHES = 'STARCHES',
  OTHER = 'OTHER',
}

export const IngredientTypeLabel: Record<IngredientType, string> = {
  [IngredientType.VEGETABLE]: 'ingredientType.vegetable',
  [IngredientType.FRUIT]: 'ingredientType.fruit',
  [IngredientType.MEAT]: 'ingredientType.meat',
  [IngredientType.FISH]: 'ingredientType.fish',
  [IngredientType.SEA_FRUIT]: 'ingredientType.seaFruit',
  [IngredientType.DAIRY]: 'ingredientType.dairy',
  [IngredientType.CHEESE]: 'ingredientType.cheese',
  [IngredientType.GRAIN]: 'ingredientType.grain',
  [IngredientType.SPICE]: 'ingredientType.spice',
  [IngredientType.CONDIMENT]: 'ingredientType.condiment',
  [IngredientType.NUT]: 'ingredientType.nut',
  [IngredientType.HERBS]: 'ingredientType.herbs',
  [IngredientType.FAT]: 'ingredientType.fat',
  [IngredientType.SUGAR]: 'ingredientType.sugar',
  [IngredientType.BEVERAGE]: 'ingredientType.beverage',
  [IngredientType.ALCOHOL]: 'ingredientType.alcohol',
  [IngredientType.STARCHES]: 'ingredientType.starches',
  [IngredientType.OTHER]: 'ingredientType.orher',
};
